apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocorp-web
  namespace: autocorp
  labels:
    app: autocorp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocorp-web
  template:
    metadata:
      name: autocorp-web
      labels:
        app: autocorp-web
    spec:
      containers:
        - name: autocorp-web
          # this still uses web.mikebarkas.com ?
          image: mikebarkas/auto-corp-web:1.0@sha256:3bcdfb1fa0b9019da0e416303ac77424d0f426c4aa28eb3f76a1df4b69b67587
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "http://postgres.postgres.svc.cluster.local:5432"
          ports:
            - containerPort: 8081
              name: web
      restartPolicy: Always

