FROM python:3.13-slim
ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/venv/bin:$PATH"
WORKDIR /app
RUN python -m venv venv
COPY requirements.txt .
RUN pip install --no-cache -r requirements.txt
COPY main.py .
ENTRYPOINT ["python", "/app/main.py"]
