apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cat
  namespace: stocker
spec:
  schedule: "40 10,12,13,15 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cat-cron
              image: mikebarkas/homelab-stocker:amd64
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: stocker-env
              env:
                - name: STOCK_SYMBOL
                  value: "CAT"
          restartPolicy: OnFailure
