apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-msft
  namespace: stocker
spec:
  schedule: "5 10,12,14,15 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: msft-cron
              image: mikebarkas/homelab-stocker:amd64
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: stocker-env
              env:
                - name: STOCK_SYMBOL
                  value: "MSFT"
          restartPolicy: OnFailure
