apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-abbv
  namespace: stocker
spec:
  schedule: "20 10,12,13,14 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: abbv-cron
              image: mikebarkas/homelab-stocker:amd64
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: stocker-env
              env:
                - name: STOCK_SYMBOL
                  value: "ABBV"
          restartPolicy: OnFailure
