apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocorp-api
  namespace: autocorp
  labels:
    app: autocorp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocorp-api
  template:
    metadata:
      name: autocorp-api
      labels:
        app: autocorp-api
    spec:
      initContainers:
        - name: psql-init
          image: alpine/psql
          envFrom:
            - secretRef:
                name: initdb-credentials
          command:
            - 'sh'
            - '-c'
            - '/initdb/init.sh'
          volumeMounts:
            - name: init
              mountPath: /initdb

      containers:
        - name: autocorp-api
          image: mikebarkas/auto-corp-api:0.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: api-credentials
          ports:
            - containerPort: 8080
              name: api
      restartPolicy: Always
      volumes:
        - name: init
          persistentVolumeClaim:
            claimName: autocorp-api-init-pvc
