apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocorp-api-init-pvc
  namespace: autocorp
  labels:
    app: autocorp-api
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
