apiVersion: v1
kind: Service
metadata:
  name: autocorp-api-svc
  namespace: autocorp
spec:
  type: ClusterIP
  selector:
    app: autocorp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
