apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data-pv
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/postgres/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-config-pv
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/postgres/config"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-init-pv
  namespace: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/postgres/init"
